import { describe, expect, it } from 'vitest';
import { writeFileSync } from 'node:fs';
import { Sim } from '@/sim/sim';
import { STAGES } from '@/sim/stages';
import { botInput } from '@/sim/bot';
import { quantizeInput } from '@/sim/replay';
import type { Difficulty } from '@/sim/defs';
import type { InputFrame } from '@/sim/types';

/**
 * Balance sweep (E10/Q7): the autopilot flies every stage on every difficulty
 * over several seeds (no cheats, unlimited lives), and we record damage taken,
 * deaths and kill rate. The autopilot is a weak pilot (no throttle, no flares),
 * so the absolute numbers are harsh — the relative curve is what gets tuned.
 *
 * Run with: BALANCE=1 pnpm vitest run tests/balance.test.ts  (writes docs/balance.md)
 */
const DIFFS: Difficulty[] = ['easy', 'normal', 'hard'];
const SEEDS = [11, 22, 33, 44, 55];

export function measure(stage: number, difficulty: Difficulty, seed: number) {
  const sim = new Sim(seed, { difficulty, dynamicDifficulty: false });
  sim.score.lives = 99;
  sim.loadStage(STAGES[stage]);
  const raw: InputFrame = { x: 0, y: 0, buttons: 0 };
  const q: InputFrame = { x: 0, y: 0, buttons: 0 };
  let shots = 0;
  sim.events.on('enemyFire', () => shots++);
  for (let t = 0; t < 60 * 240 && sim.state === 'playing'; t++)
    sim.step(quantizeInput(botInput(sim, raw), q));
  const s = sim.score.stats;
  return {
    damage: s.damageTaken,
    deaths: s.deaths,
    kill: s.spawned ? s.kills / s.spawned : 0,
    shots,
    cleared: sim.state === 'cleared',
  };
}

describe.skipIf(!process.env.BALANCE)('balance sweep', () => {
  it('measures every stage × difficulty', () => {
    const rows: string[] = [
      '| Stage | ' + DIFFS.map((d) => `${d} dmg / deaths / kill%`).join(' | ') + ' |',
      '| --- | --- | --- | --- |',
    ];
    const curve: Record<Difficulty, number[]> = { easy: [], normal: [], hard: [] };
    STAGES.forEach((def, i) => {
      const cells = DIFFS.map((d) => {
        const r = SEEDS.map((seed) => measure(i, d, seed));
        const avg = (k: 'damage' | 'deaths' | 'kill') => r.reduce((a, x) => a + x[k], 0) / r.length;
        curve[d].push(avg('damage'));
        return `${avg('damage').toFixed(1)} / ${avg('deaths').toFixed(1)} / ${Math.round(avg('kill') * 100)}%`;
      });
      rows.push(`| ${def.index} ${def.name} | ${cells.join(' | ')} |`);
    });
    const md = `# Balance sweep\n\nAutopilot (weak pilot: no throttle, no flares) · seeds ${SEEDS.join(', ')} · averages per stage.\nGenerated by \`BALANCE=1 pnpm vitest run tests/balance.test.ts\`.\n\n${rows.join('\n')}\n`;
    writeFileSync('docs/balance.md', md);
    console.log(md);
    // Difficulty ordering must hold on every stage.
    for (let i = 0; i < STAGES.length; i++) expect(curve.easy[i]).toBeLessThanOrEqual(curve.hard[i] + 0.5);
  }, 600_000);
});
