import {
  ace,
  bossCore,
  bossEngine,
  bossTurret,
  chaser,
  drone,
  fighter,
  fortressHull,
  missile,
  playerJet,
  type ModelGeo,
} from './models';
import {
  aaa,
  awacs,
  bomber,
  bossBridge,
  bossSam,
  carrier,
  destroyer,
  gunship,
  missileBoat,
  playerDart,
  playerManta,
  sam,
  tank,
  tanker,
} from './models-m3';

/** Model key (as used by simulation entities) → procedural geometry factory. */
export const MODEL_FACTORIES: Record<string, () => ModelGeo> = {
  player: playerJet,
  playerDart,
  playerManta,
  fighter,
  chaser,
  drone,
  ace,
  bomber,
  gunship,
  awacs,
  sam,
  aaa,
  tank,
  destroyer,
  missileboat: missileBoat,
  missile: () => missile(false),
  emissile: () => missile(true),
  fortress: fortressHull,
  bossTurret,
  bossEngine,
  bossCore,
  carrier,
  bossDestroyer: destroyer,
  bossSam,
  bossBridge,
  tanker,
};

/** Render-only scale so small silhouettes stay readable at arcade speed. */
export const MODEL_SCALE: Record<string, number> = {
  fighter: 1.7,
  chaser: 1.6,
  drone: 1.8,
  ace: 1.7,
  bomber: 1.2,
  gunship: 1.4,
  awacs: 1.2,
  sam: 3.6,
  aaa: 4,
  tank: 4.4,
  destroyer: 1.5,
  missileboat: 2.2,
  missile: 1.3,
  emissile: 1.6,
};

/** Max simultaneous instances per model. */
export const CAPACITY: Record<string, number> = {
  fighter: 48,
  chaser: 24,
  drone: 96,
  ace: 8,
  bomber: 8,
  gunship: 8,
  awacs: 2,
  sam: 12,
  aaa: 16,
  tank: 24,
  destroyer: 6,
  missileboat: 12,
  missile: 64,
  emissile: 48,
  fortress: 1,
  bossTurret: 8,
  bossEngine: 4,
  bossCore: 2,
  carrier: 1,
  bossDestroyer: 2,
  bossSam: 2,
  bossBridge: 1,
  tanker: 1,
};
