// K9: third-party notices for everything that ships (game bundle + API function).
// Walks production dependencies and writes public/licenses.txt + docs/THIRD_PARTY_NOTICES.md.
import { existsSync, readdirSync, readFileSync, realpathSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const root = JSON.parse(readFileSync('package.json', 'utf8'));
const seen = new Map();

function resolve(name, from) {
  let dir = from;
  while (true) {
    const p = join(dir, 'node_modules', name, 'package.json');
    if (existsSync(p)) return realpathSync(p);
    const up = dirname(dir);
    if (up === dir) return null;
    dir = up;
  }
}

function visit(name, from) {
  const pj = resolve(name, from);
  if (!pj) return;
  const pkg = JSON.parse(readFileSync(pj, 'utf8'));
  const key = `${pkg.name}@${pkg.version}`;
  if (seen.has(key)) return;
  const dir = dirname(pj);
  const file = readdirSync(dir).find((f) => /^(licen[cs]e|copying)(\.|$)/i.test(f));
  seen.set(key, {
    name: pkg.name,
    version: pkg.version,
    license: typeof pkg.license === 'string' ? pkg.license : (pkg.license?.type ?? 'UNKNOWN'),
    text: file ? readFileSync(join(dir, file), 'utf8').trim() : '',
  });
  for (const dep of Object.keys(pkg.dependencies ?? {})) visit(dep, dir);
}

for (const dep of Object.keys(root.dependencies ?? {})) visit(dep, process.cwd());
const list = [...seen.values()].sort((a, b) => a.name.localeCompare(b.name));

const txt =
  `Hot Tail — third-party software notices\n\nHot Tail includes the following open-source packages.\n\n` +
  list
    .map(
      (p) =>
        `${'='.repeat(72)}\n${p.name} ${p.version} (${p.license})\n${'='.repeat(72)}\n${p.text || '(license text not bundled with the package)'}\n`,
    )
    .join('\n');
writeFileSync('public/licenses.txt', txt);
writeFileSync(
  'docs/THIRD_PARTY_NOTICES.md',
  `# Third-party notices\n\nGenerated by \`node scripts/licenses.mjs\` from production dependencies (shipped in the game bundle or the API function). Full texts: [public/licenses.txt](../public/licenses.txt), served at \`/licenses.txt\`.\n\n| Package | Version | License |\n| --- | --- | --- |\n` +
    list.map((p) => `| ${p.name} | ${p.version} | ${p.license} |`).join('\n') +
    '\n\nDev-only tools (Vite, TypeScript, Vitest, Playwright, ESLint, esbuild, PGlite) are not distributed.\n',
);
console.log(list.map((p) => `${p.name}@${p.version} ${p.license}`).join('\n'));
const bad = list.filter(
  (p) => !/^(MIT|ISC|BSD-2-Clause|BSD-3-Clause|Apache-2\.0|0BSD|MIT-0)$/.test(p.license),
);
if (bad.length) {
  console.error('Licences needing review:', bad.map((p) => `${p.name} (${p.license})`).join(', '));
  process.exitCode = 1;
}
